-- Initial real Fall 2026 Couch Sloth library recovered from the approved master list.
insert into public.titles(id,title,type,format,description,legacy_platform,metadata_source)
values
('american-horror-story-13','American Horror Story: 13','Series','series','Season 13. Added from the Fall 2026 Couch Sloth master list.','Hulu','manual'),
('shark-tank','Shark Tank','Series','series','Season 18. Returning favorite.','Hulu','manual'),
('war','WAR','Series','series','New series from the Fall 2026 list.','HBO Max','manual'),
('east-of-eden','East of Eden','Series','series','Limited prestige family drama.','Netflix','manual'),
('lorne','Lorne','Documentary','film','Lorne Michaels and SNL.','Netflix','manual'),
('nepals-deadly-floods','Nepal’s Deadly Floods','Documentary','film','Disaster and current-events documentary.','HBO Max','manual'),
('carrie','Carrie','Series','series','Mike Flanagan’s Stephen King adaptation; full-season binge.','Prime Video','manual'),
('abbott-elementary','Abbott Elementary','Series','series','Season 6. Returning favorite.','Hulu','manual'),
('the-serial-killer-connection','The Serial Killer Connection','Documentary','series','True-crime docuseries.','HBO Max','manual'),
('top-of-the-world','Top of the World','Documentary','film','Windows on the World and 9/11.','HBO Max','manual'),
('below','Below','Series','series','Newfoundland creature and family drama.','Netflix','manual'),
('rage','Rage','Series','series','Track all seasons.','HBO Max','manual'),
('oasis-dont-look-back-in-anger','Oasis: Don’t Look Back in Anger','Documentary','film','Music documentary.','Hulu','manual'),
('the-first-monday-in-may','The First Monday in May','Documentary','film','Older documentary newly available.','Netflix','manual'),
('the-pet-cemetery-murders','The Pet Cemetery Murders: A Ghost Story','Documentary','series','True-crime docuseries.','HBO Max','manual'),
('clown-panic','Clown Panic','Documentary','film','Documentary about the 2016 creepy-clown panic.','Hulu','manual'),
('free-leonard-peltier','Free Leonard Peltier','Documentary','film','Indigenous activist and criminal-justice documentary.','Netflix','manual'),
('tyson','TYSON','Documentary','series','Mike Tyson docuseries.','Netflix','manual'),
('visionquest','VisionQuest','Series','series','Vision, Ultron, AI and personhood.','Disney+','manual'),
('the-diplomat','The Diplomat','Series','series','Track all seasons; start at Season 1.','Netflix','manual'),
('the-disciple-a-wu-tang-fable','The Disciple: A Wu-Tang Fable','Documentary','film','Wu-Tang secret-album documentary.','Netflix','manual'),
('norm-the-tale-of-norm-macdonald','Norm: The Tale of Norm Macdonald','Documentary','film','Norm Macdonald documentary.','Netflix','manual'),
('super-scam-me','Super Scam Me','Documentary','series','Scam-focused docuseries.','Hulu','manual'),
('phony','Phony','Series','series','Psychological and paranoid thriller.','Hulu','manual'),
('the-flores-massacre','The Flores Massacre','Documentary','series','True-crime docuseries.','HBO Max','manual'),
('nobody-wants-this','Nobody Wants This','Series','series','Track Seasons 1–3; start at Season 1.','Netflix','manual'),
('lupin','Lupin','Series','series','Track Parts 1–4; start at Part 1.','Netflix','manual'),
('surviving-hurricane-otis','Surviving Hurricane Otis','Series','series','Scripted drama; originally misclassified as a documentary in the discovery list.','Netflix','manual'),
('monsters-truth-behind-the-myths','Monsters: Truth Behind the Myths','Documentary','series','Monsters, legends and folklore docuseries.','Hulu','manual'),
('dolly','Dolly','Documentary','film','Older documentary newly available.','Hulu','manual'),
('the-wolves-of-real-estate','The Wolves of Real Estate','Documentary','series','True-crime docuseries.','Peacock','manual'),
('30-days-inside-hospitals-and-the-immigrant-workforce','30 Days Inside: Hospitals and the Immigrant Workforce','Documentary','film','Healthcare and immigration documentary.','HBO Max','manual'),
('in-pursuit-lessons-of-american-leadership','In Pursuit: Lessons of American Leadership','Documentary','film','American leadership documentary.','PBS','manual'),
('the-one-about-matthew-perry','The One About Matthew Perry','Documentary','series','Matthew Perry, addiction and recovery.','Netflix','manual'),
('cannibal-poet','Cannibal Poet','Documentary','series','Serial-killer case docuseries.','HBO Max','manual'),
('the-gilded-age','The Gilded Age','Series','series','Track all seasons; start at Season 1.','HBO Max','manual'),
('awkwafina-the-unlikely-cook','Awkwafina: The Unlikely Cook','Documentary','series','Food, family and cultural-history docuseries.','Apple TV','manual'),
('we-chose-to-go-to-the-moon','We Chose to Go to the Moon','Documentary','film','Apollo and space-history documentary.','PBS','manual'),
('humanlike-the-chimps-of-fongoli','HumanLike: The Chimps of Fongoli','Documentary','film','Chimp-behavior documentary.','PBS','manual'),
('blade-runner-2099','Blade Runner 2099','Series','series','New prestige science-fiction series.','Prime Video','manual'),
('the-hunting-wives','The Hunting Wives','Series','series','Season 1 watched; Season 2 tracked for release.','Netflix','manual'),
('pride-and-prejudice','Pride and Prejudice','Series','series','New adaptation.','Netflix','manual'),
('14th','14TH','Documentary','film','Ava DuVernay documentary about the 14th Amendment.','Netflix','manual'),
('only-murders-in-the-building','Only Murders in the Building','Series','series','Season 6. Returning murder-comedy.','Hulu','manual'),
('the-murder-of-jonbenet-ramsey','The Murder of JonBenét Ramsey','Documentary','series','Approved true-crime docuseries.','Netflix','manual'),
('harry-potter-hbo','Harry Potter and the Philosopher’s Stone','Series','series','New HBO adaptation begins. FOR SURE.','HBO Max','manual')
on conflict(id) do update set
  title=excluded.title,
  type=excluded.type,
  format=excluded.format,
  description=case when public.titles.description='' then excluded.description else public.titles.description end,
  legacy_platform=excluded.legacy_platform;

insert into public.streaming_availability(title_id,provider,region,status,release_date,metadata_source,checked_at)
values
('american-horror-story-13','Hulu','US','available','2026-09-24','manual',now()),
('shark-tank','Hulu','US','available','2026-09-30','manual',now()),
('war','HBO Max','US','available','2026-10-01','manual',now()),
('east-of-eden','Netflix','US','available','2026-10-01','manual',now()),
('lorne','Netflix','US','upcoming','2026-10-05','manual',now()),
('nepals-deadly-floods','HBO Max','US','upcoming','2026-10-06','manual',now()),
('carrie','Prime Video','US','upcoming','2026-10-07','manual',now()),
('abbott-elementary','Hulu','US','upcoming','2026-10-07','manual',now()),
('the-serial-killer-connection','HBO Max','US','upcoming','2026-10-07','manual',now()),
('top-of-the-world','HBO Max','US','upcoming','2026-10-08','manual',now()),
('below','Netflix','US','upcoming','2026-10-08','manual',now()),
('rage','HBO Max','US','upcoming','2026-10-09','manual',now()),
('oasis-dont-look-back-in-anger','Hulu','US','upcoming','2026-10-09','manual',now()),
('the-first-monday-in-may','Netflix','US','upcoming','2026-10-10','manual',now()),
('the-pet-cemetery-murders','HBO Max','US','upcoming','2026-10-11','manual',now()),
('clown-panic','Hulu','US','upcoming','2026-10-12','manual',now()),
('free-leonard-peltier','Netflix','US','upcoming','2026-10-12','manual',now()),
('tyson','Netflix','US','upcoming','2026-10-13','manual',now()),
('visionquest','Disney+','US','upcoming','2026-10-14','manual',now()),
('the-diplomat','Netflix','US','upcoming','2026-10-15','manual',now()),
('the-disciple-a-wu-tang-fable','Netflix','US','upcoming','2026-10-16','manual',now()),
('norm-the-tale-of-norm-macdonald','Netflix','US','upcoming','2026-10-16','manual',now()),
('super-scam-me','Hulu','US','upcoming','2026-10-18','manual',now()),
('phony','Hulu','US','upcoming','2026-10-20','manual',now()),
('the-flores-massacre','HBO Max','US','upcoming','2026-10-22','manual',now()),
('nobody-wants-this','Netflix','US','upcoming','2026-10-22','manual',now()),
('lupin','Netflix','US','upcoming','2026-10-23','manual',now()),
('surviving-hurricane-otis','Netflix','US','upcoming','2026-10-23','manual',now()),
('monsters-truth-behind-the-myths','Hulu','US','upcoming','2026-10-24','manual',now()),
('dolly','Hulu','US','upcoming','2026-10-24','manual',now()),
('the-wolves-of-real-estate','Peacock','US','upcoming','2026-10-25','manual',now()),
('30-days-inside-hospitals-and-the-immigrant-workforce','HBO Max','US','upcoming','2026-10-27','manual',now()),
('in-pursuit-lessons-of-american-leadership','PBS','US','upcoming','2026-10-27','manual',now()),
('the-one-about-matthew-perry','Netflix','US','upcoming','2026-10-28','manual',now()),
('cannibal-poet','HBO Max','US','upcoming','2026-10-29','manual',now()),
('the-gilded-age','HBO Max','US','upcoming','2026-11-01','manual',now()),
('awkwafina-the-unlikely-cook','Apple TV','US','upcoming','2026-11-06','manual',now()),
('we-chose-to-go-to-the-moon','PBS','US','upcoming','2026-11-10','manual',now()),
('humanlike-the-chimps-of-fongoli','PBS','US','upcoming','2026-11-11','manual',now()),
('blade-runner-2099','Prime Video','US','upcoming','2026-11-25','manual',now()),
('the-hunting-wives','Netflix','US','upcoming','2026-11-26','manual',now()),
('pride-and-prejudice','Netflix','US','upcoming','2026-12-03','manual',now()),
('14th','Netflix','US','upcoming','2026-12-04','manual',now()),
('only-murders-in-the-building','Hulu','US','upcoming','2026-12-08','manual',now()),
('the-murder-of-jonbenet-ramsey','Netflix','US','upcoming','2026-12-10','manual',now()),
('harry-potter-hbo','HBO Max','US','upcoming','2026-12-25','manual',now())
on conflict(title_id,provider,region) do update set
  status=excluded.status,
  release_date=excluded.release_date,
  metadata_source=excluded.metadata_source,
  checked_at=excluded.checked_at;

insert into public.seasons(title_id,season_number,name,release_date,metadata_source)
values
('american-horror-story-13',13,'Season 13','2026-09-24','manual'),
('shark-tank',18,'Season 18','2026-09-30','manual'),
('war',1,'Season 1','2026-10-01','manual'),
('east-of-eden',1,'Season 1','2026-10-01','manual'),
('carrie',1,'Season 1','2026-10-07','manual'),
('abbott-elementary',6,'Season 6','2026-10-07','manual'),
('below',1,'Season 1','2026-10-08','manual'),
('visionquest',1,'Season 1','2026-10-14','manual'),
('the-diplomat',1,'Season 1',null,'manual'),
('the-diplomat',2,'Season 2',null,'manual'),
('the-diplomat',3,'Season 3',null,'manual'),
('the-diplomat',4,'Season 4','2026-10-15','manual'),
('phony',1,'Season 1','2026-10-20','manual'),
('nobody-wants-this',1,'Season 1',null,'manual'),
('nobody-wants-this',2,'Season 2',null,'manual'),
('nobody-wants-this',3,'Season 3','2026-10-22','manual'),
('lupin',1,'Part 1',null,'manual'),
('lupin',2,'Part 2',null,'manual'),
('lupin',3,'Part 3',null,'manual'),
('lupin',4,'Part 4','2026-10-23','manual'),
('surviving-hurricane-otis',1,'Season 1','2026-10-23','manual'),
('the-gilded-age',1,'Season 1',null,'manual'),
('the-gilded-age',2,'Season 2',null,'manual'),
('the-gilded-age',3,'Season 3',null,'manual'),
('the-gilded-age',4,'Season 4','2026-11-01','manual'),
('blade-runner-2099',1,'Season 1','2026-11-25','manual'),
('the-hunting-wives',1,'Season 1',null,'manual'),
('the-hunting-wives',2,'Season 2','2026-11-26','manual'),
('pride-and-prejudice',1,'Season 1','2026-12-03','manual'),
('only-murders-in-the-building',6,'Season 6','2026-12-08','manual'),
('harry-potter-hbo',1,'Season 1','2026-12-25','manual')
on conflict(title_id,season_number) do update set
  name=excluded.name,
  release_date=coalesce(excluded.release_date,public.seasons.release_date),
  metadata_source=excluded.metadata_source;

insert into public.watch_progress(profile_id,title_id,status,tracking_intent,updated_at)
values
('parker','american-horror-story-13','watchlist','all',now()),
('parker','shark-tank','watchlist','all',now()),
('parker','war','watchlist','all',now()),
('parker','east-of-eden','watchlist','all',now()),
('parker','lorne','watchlist','all',now()),
('parker','nepals-deadly-floods','watchlist','all',now()),
('parker','carrie','watchlist','all',now()),
('parker','abbott-elementary','watchlist','all',now()),
('parker','the-serial-killer-connection','watchlist','all',now()),
('parker','top-of-the-world','watchlist','all',now()),
('parker','below','watchlist','all',now()),
('parker','rage','watchlist','all',now()),
('parker','oasis-dont-look-back-in-anger','watchlist','all',now()),
('parker','the-first-monday-in-may','watchlist','all',now()),
('parker','the-pet-cemetery-murders','watchlist','all',now()),
('parker','clown-panic','watchlist','all',now()),
('parker','free-leonard-peltier','watchlist','all',now()),
('parker','tyson','watchlist','all',now()),
('parker','visionquest','watchlist','all',now()),
('parker','the-diplomat','watchlist','all',now()),
('parker','the-disciple-a-wu-tang-fable','watchlist','all',now()),
('parker','norm-the-tale-of-norm-macdonald','watchlist','all',now()),
('parker','super-scam-me','watchlist','all',now()),
('parker','phony','watchlist','all',now()),
('parker','the-flores-massacre','watchlist','all',now()),
('parker','nobody-wants-this','watchlist','all',now()),
('parker','lupin','watchlist','all',now()),
('parker','surviving-hurricane-otis','watchlist','all',now()),
('parker','monsters-truth-behind-the-myths','watchlist','all',now()),
('parker','dolly','watchlist','all',now()),
('parker','the-wolves-of-real-estate','watchlist','all',now()),
('parker','30-days-inside-hospitals-and-the-immigrant-workforce','watchlist','all',now()),
('parker','in-pursuit-lessons-of-american-leadership','watchlist','all',now()),
('parker','the-one-about-matthew-perry','watchlist','all',now()),
('parker','cannibal-poet','watchlist','all',now()),
('parker','the-gilded-age','watchlist','all',now()),
('parker','awkwafina-the-unlikely-cook','watchlist','all',now()),
('parker','we-chose-to-go-to-the-moon','watchlist','all',now()),
('parker','humanlike-the-chimps-of-fongoli','watchlist','all',now()),
('parker','blade-runner-2099','watchlist','all',now()),
('parker','the-hunting-wives','caught_up','all',now()),
('parker','pride-and-prejudice','watchlist','all',now()),
('parker','14th','watchlist','all',now()),
('parker','only-murders-in-the-building','watchlist','all',now()),
('parker','the-murder-of-jonbenet-ramsey','watchlist','all',now()),
('parker','harry-potter-hbo','watchlist','all',now())
on conflict(profile_id,title_id) do nothing;

insert into public.season_progress(profile_id,season_id,watched,updated_at)
select 'parker',s.id,true,now()
from public.seasons s
where s.title_id='the-hunting-wives' and s.season_number=1
on conflict(profile_id,season_id) do update set watched=true,updated_at=now();

update public.watch_progress
set status='caught_up',tracking_intent='all',updated_at=now()
where profile_id='parker' and title_id='the-hunting-wives';
